export enum WriteDownEditorActions {
  ON_NEW_LINE,
  ON_DELETE_LINE,
  ON_CONTENT_CHANGE,
  ON_MOVE_BY_LINE,
  ON_ARROW_KEY_UP,
  ON_ARROW_KEY_DOWN,
  ON_UPDATE_CURRENT_LINE_NUMBER,
  ON_UPDATE_CURRENT_COLUMN_NUMBER
}
